"""Audit and console-debug helpers for the screening assistant."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
import json
import os
import re
from typing import Any, cast

from langgraph.config import get_stream_writer

from screening_agent.config import ConsoleDebugMode
from screening_agent.graph.state import AuditEvent

_MAX_CONSOLE_TEXT_LENGTH = 4_000
_SECURITY_NUMBER_PATTERN = re.compile(r"\b(\d{4})(\d{4})\b")
_FLOW_DEBUG_EVENT_TYPES: frozenset[str] = frozenset({"task", "task_result"})



def emit_console_audit(event: AuditEvent) -> None:
    """Emit a structured audit event to stdout.

    Args:
        event: Serializable audit event generated by the graph or a tool.
    """

    if not _is_console_json_debug_enabled():
        return

    _emit_json_line(_build_audit_console_event(event))


def _is_console_json_debug_enabled() -> bool:
    """Return whether JSON debug output should be emitted to the terminal.

    Returns:
        `True` when console JSON output is enabled.
    """

    return _get_console_debug_mode() == "debug"


def _get_console_debug_mode() -> ConsoleDebugMode:
    """Read the current console debug mode from the process environment.

    Returns:
        The normalized console debug mode.
    """

    raw_value = os.getenv("SCREENING_AGENT_CONSOLE_DEBUG_MODE", "none").strip().lower()
    if raw_value not in {"none", "info", "debug"}:
        return "none"
    return cast(ConsoleDebugMode, raw_value)


def emit_console_stream_part(
    part: Mapping[str, Any],
    *,
    thread_id: str | None = None,
) -> bool:
    """Emit a filtered LangGraph flow event to stdout as structured JSON.

    Args:
        part: Stream part emitted by LangGraph streaming in `version="v2"` format.
        thread_id: Optional thread identifier used to correlate terminal events.

    Returns:
        `True` when a flow-oriented console line was emitted, otherwise `False`.
    """

    if part.get("type") != "debug":
        return False

    if not _is_flow_debug_stream_part(part.get("data")):
        return False

    _emit_json_line(_build_stream_console_event(part, thread_id=thread_id))
    return True


def emit_verbose_console_stream_part(
    part: Mapping[str, Any],
    *,
    thread_id: str | None = None,
) -> bool:
    """Emit a LangGraph stream part without filtering token-level events.

    Args:
        part: Stream part emitted by LangGraph streaming in `version="v2"` format.
        thread_id: Optional thread identifier used to correlate terminal events.

    Returns:
        Always `True`, because verbose mode emits every provided stream part.
    """

    _emit_json_line(
        _sanitize_for_console(
            {
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "event_class": "langgraph_stream",
                "thread_id": thread_id,
                "type": part.get("type"),
                "ns": part.get("ns", ()),
                "data": part.get("data"),
            },
        ),
    )
    return True


def _build_audit_console_event(event: AuditEvent) -> dict[str, object]:
    """Build the compact console JSON emitted for audit events.

    Args:
        event: Raw audit event created by a node or tool.

    Returns:
        Sanitized compact console payload.
    """

    sanitized_event = _sanitize_for_console(
        {
            "timestamp_utc": event["timestamp_utc"],
            "event_class": "audit",
            "thread_id": _normalize_thread_id(None),
            "execution": {
                "event_type": event["event_type"],
                "status": event["status"],
                "node_name": event["node_name"],
                "detail": event["detail"],
            },
        },
    )
    if isinstance(sanitized_event, dict):
        return sanitized_event
    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "audit",
        "thread_id": _normalize_thread_id(None),
        "execution": {"detail": str(sanitized_event)},
    }


def _build_stream_console_event(
    part: Mapping[str, Any],
    *,
    thread_id: str | None,
) -> dict[str, object]:
    """Build the compact console JSON emitted for a streamed LangGraph part.

    Args:
        part: LangGraph stream part emitted in `version="v2"` format.
        thread_id: Optional thread identifier used to correlate console output.

    Returns:
        Sanitized compact console payload.
    """

    sanitized_event = _sanitize_for_console(
        {
            "timestamp_utc": datetime.now(timezone.utc).isoformat(),
            "event_class": "langgraph_stream",
            "thread_id": _normalize_thread_id(thread_id),
            "execution": _summarize_stream_execution(part),
        },
    )
    if isinstance(sanitized_event, dict):
        return sanitized_event
    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "langgraph_stream",
        "thread_id": _normalize_thread_id(thread_id),
        "execution": {"detail": str(sanitized_event)},
    }


def _is_flow_debug_stream_part(data: object) -> bool:
    """Return whether a debug stream payload represents a flow event to log.

    Args:
        data: Raw `debug` payload emitted by LangGraph.

    Returns:
        `True` for task transition events, otherwise `False`.
    """

    if not isinstance(data, Mapping):
        return False

    debug_event_type = data.get("type")
    return isinstance(debug_event_type, str) and debug_event_type in _FLOW_DEBUG_EVENT_TYPES


def _summarize_stream_execution(part: Mapping[str, Any]) -> dict[str, object]:
    """Summarize a streamed LangGraph part for concise console output.

    Args:
        part: Raw stream part.

    Returns:
        Compact execution summary with only the most informative fields.
    """

    part_type = part.get("type")
    data = part.get("data")
    execution_summary: dict[str, object] = {
        "stream_type": part_type,
        "namespace": _format_namespace(part.get("ns")),
    }
    execution_summary.update(_summarize_stream_data(part_type=part_type, data=data))
    return execution_summary


def _normalize_thread_id(thread_id: str | None) -> str:
    """Normalize an optional thread identifier for console output.

    Args:
        thread_id: Optional thread identifier.

    Returns:
        Provided thread identifier when available, otherwise `"n/a"`.
    """

    normalized_thread_id = (thread_id or "").strip()
    return normalized_thread_id or "n/a"


def _format_namespace(value: object) -> str | None:
    """Convert a namespace tuple into a compact console string.

    Args:
        value: Raw namespace payload emitted by LangGraph.

    Returns:
        Slash-separated namespace or `None` when unavailable.
    """

    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        normalized_items = [str(item) for item in value if str(item).strip()]
        if normalized_items:
            return " / ".join(normalized_items)
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None


def _summarize_stream_data(*, part_type: object, data: object) -> dict[str, object]:
    """Summarize the execution details associated with a streamed part.

    Args:
        part_type: Stream part type.
        data: Raw stream-part payload.

    Returns:
        Compact execution fields suitable for console logging.
    """

    if part_type == "values":
        values_summary = _summarize_values_payload(data)
        if isinstance(values_summary, Mapping):
            return {str(key): value for key, value in values_summary.items()}
        return {"summary": values_summary}

    if isinstance(data, Mapping):
        return _collect_internal_execution_fields(data)

    if data is None:
        return {}
    return {"summary": data}


def _collect_internal_execution_fields(value: Mapping[str, object]) -> dict[str, object]:
    """Extract concise execution metadata from a stream payload.

    Args:
        value: Raw stream payload mapping.

    Returns:
        Compact dictionary without the original payload content.
    """

    summarized_fields: dict[str, object] = {}
    for key in (
        "event_name",
        "event_type",
        "status",
        "node_name",
        "langgraph_node",
        "step",
        "checkpoint_ns",
        "task_id",
        "id",
        "triggers",
        "error",
    ):
        _set_summary_field(summarized_fields, key, value.get(key))

    if "node_name" not in summarized_fields:
        _set_summary_field(summarized_fields, "node_name", value.get("name"))

    _set_summary_field(summarized_fields, "internal_type", value.get("type"))

    payload = value.get("payload")
    if isinstance(payload, Mapping):
        payload_fields = _collect_payload_execution_fields(payload)
        for key, nested_value in payload_fields.items():
            summarized_fields.setdefault(key, nested_value)

    if summarized_fields:
        return summarized_fields
    return {"keys": sorted(str(key) for key in value.keys())}


def _collect_payload_execution_fields(value: Mapping[str, object]) -> dict[str, object]:
    """Extract concise execution metadata from a nested `payload` mapping.

    Args:
        value: Nested payload mapping.

    Returns:
        Compact metadata fields.
    """

    summarized_fields: dict[str, object] = {}
    for key in (
        "event_name",
        "event_type",
        "status",
        "node_name",
        "langgraph_node",
        "step",
        "checkpoint_ns",
        "task_id",
        "id",
        "triggers",
        "error",
    ):
        _set_summary_field(summarized_fields, key, value.get(key))

    if "node_name" not in summarized_fields:
        _set_summary_field(summarized_fields, "node_name", value.get("name"))

    return summarized_fields


def _set_summary_field(
    target: dict[str, object],
    key: str,
    value: object,
) -> None:
    """Set a summarized execution field when the value is informative.

    Args:
        target: Mutable summary dictionary.
        key: Output field name.
        value: Candidate field value.
    """

    if value is None:
        return
    if isinstance(value, str) and not value.strip():
        return
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        if not value:
            return
    target[key] = value


def create_debug_event(
    event_name: str,
    *,
    payload: Mapping[str, Any] | None = None,
    **context: object,
) -> dict[str, object]:
    """Create a JSON-compatible debug event payload.

    Args:
        event_name: Stable event name describing the debug payload.
        payload: Optional event-specific payload.
        **context: Additional event metadata.

    Returns:
        Sanitized dictionary ready for stream-writer emission or terminal output.
    """

    raw_event: dict[str, object] = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "custom_debug",
        "event_name": event_name,
    }
    raw_event.update({key: value for key, value in context.items() if value is not None})
    if payload is not None:
        raw_event["payload"] = payload
    sanitized_event = _sanitize_for_console(raw_event)
    if isinstance(sanitized_event, dict):
        return sanitized_event
    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "custom_debug",
        "event_name": "debug_event_serialization_error",
        "payload": str(sanitized_event),
    }


def emit_custom_debug_event(
    event_name: str,
    *,
    payload: Mapping[str, Any] | None = None,
    **context: object,
) -> None:
    """Emit a custom LangGraph debug event through the stream writer when available.

    Args:
        event_name: Stable event name describing the debug payload.
        payload: Optional event payload.
        **context: Additional event metadata.
    """

    try:
        writer = get_stream_writer()
    except Exception:
        return

    if not callable(writer):
        return
    writer(create_debug_event(event_name, payload=payload, **context))


def _emit_json_line(payload: object) -> None:
    """Print a JSON payload as one console line.

    Args:
        payload: JSON-compatible payload to emit.
    """

    print(json.dumps(payload, ensure_ascii=False))


def _sanitize_for_console(value: object) -> object:
    """Convert arbitrary values into JSON-friendly console output.

    Args:
        value: Arbitrary Python value.

    Returns:
        JSON-compatible sanitized representation.
    """

    if value is None or isinstance(value, bool | int | float):
        return value
    if isinstance(value, str):
        return _truncate_text(_mask_security_numbers(value))
    if isinstance(value, Mapping):
        return {
            str(key): _sanitize_for_console(nested_value)
            for key, nested_value in value.items()
            if nested_value is not None
        }
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return [_sanitize_for_console(item) for item in value]
    if hasattr(value, "model_dump") and callable(value.model_dump):
        return _sanitize_for_console(value.model_dump())
    if hasattr(value, "dict") and callable(value.dict):
        return _sanitize_for_console(value.dict())
    return _truncate_text(_mask_security_numbers(str(value)))


def _summarize_values_payload(value: object) -> object:
    """Summarize a streamed `values` payload for standard console mode.

    Args:
        value: Raw streamed state payload.

    Returns:
        A compact JSON-compatible summary.
    """

    normalized_value = value
    if hasattr(normalized_value, "model_dump") and callable(normalized_value.model_dump):
        normalized_value = normalized_value.model_dump()
    elif hasattr(normalized_value, "dict") and callable(normalized_value.dict):
        normalized_value = normalized_value.dict()

    if not isinstance(normalized_value, Mapping):
        return normalized_value

    specialist_output_json = normalized_value.get("specialist_output_json")
    specialist_support_status = None
    if isinstance(specialist_output_json, str) and specialist_output_json.strip():
        try:
            specialist_output = json.loads(specialist_output_json)
        except json.JSONDecodeError:
            specialist_output = None
        if isinstance(specialist_output, Mapping):
            specialist_support_status = specialist_output.get("support_status")

    message_count = normalized_value.get("messages", [])

    return {
        "keys": sorted(str(key) for key in normalized_value.keys()),
        "router_intent": normalized_value.get("router_intent"),
        "patient_lookup_status": normalized_value.get("patient_lookup_status"),
        "specialist_support_status": specialist_support_status,
        "has_active_patient": normalized_value.get("active_patient") is not None,
        "has_last_response": bool(str(normalized_value.get("last_response") or "").strip()),
        "message_count": len(message_count) if isinstance(message_count, list) else 0,
    }


def _mask_security_numbers(text: str) -> str:
    """Mask fictional 8-digit security numbers before console emission.

    Args:
        text: Text that may contain patient identifiers.

    Returns:
        Text with 8-digit identifiers masked to preserve only the last four digits.
    """

    return _SECURITY_NUMBER_PATTERN.sub(r"****\2", text)


def _truncate_text(text: str) -> str:
    """Truncate long console strings while preserving that truncation occurred.

    Args:
        text: Text to potentially truncate.

    Returns:
        Original text when short enough, otherwise a truncated representation.
    """

    if len(text) <= _MAX_CONSOLE_TEXT_LENGTH:
        return text
    truncated_characters = len(text) - _MAX_CONSOLE_TEXT_LENGTH
    return (
        f"{text[:_MAX_CONSOLE_TEXT_LENGTH]}"
        f"… [truncated {truncated_characters} chars]"
    )
