"""Audit and console-debug helpers for the screening assistant."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from datetime import datetime, timezone
import json
import re
from typing import Any

from langgraph.config import get_stream_writer

from screening_agent.graph.state import AuditEvent

_MAX_CONSOLE_TEXT_LENGTH = 4_000
_SECURITY_NUMBER_PATTERN = re.compile(r"\b(\d{4})(\d{4})\b")



def emit_console_audit(event: AuditEvent) -> None:
    """Emit a structured audit event to stdout.

    Args:
        event: Serializable audit event generated by the graph or a tool.
    """

    _emit_json_line(_sanitize_for_console(event))


def emit_console_stream_part(
    part: Mapping[str, Any],
    *,
    thread_id: str | None = None,
) -> bool:
    """Emit a LangGraph stream part to stdout as structured JSON.

    Args:
        part: Stream part emitted by LangGraph streaming in `version="v2"` format.
        thread_id: Optional thread identifier used to correlate terminal events.

    Returns:
        `True` when a console line was emitted, otherwise `False`.
    """

    if part.get("type") == "messages":
        return False

    data = part.get("data")
    if part.get("type") == "values":
        data = _summarize_values_payload(data)

    _emit_json_line(
        _sanitize_for_console(
            {
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "event_class": "langgraph_stream",
                "thread_id": thread_id,
                "type": part.get("type"),
                "ns": part.get("ns", ()),
                "data": data,
            },
        ),
    )
    return True


def emit_verbose_console_stream_part(
    part: Mapping[str, Any],
    *,
    thread_id: str | None = None,
) -> bool:
    """Emit a LangGraph stream part without filtering token-level events.

    Args:
        part: Stream part emitted by LangGraph streaming in `version="v2"` format.
        thread_id: Optional thread identifier used to correlate terminal events.

    Returns:
        Always `True`, because verbose mode emits every provided stream part.
    """

    _emit_json_line(
        _sanitize_for_console(
            {
                "timestamp_utc": datetime.now(timezone.utc).isoformat(),
                "event_class": "langgraph_stream",
                "thread_id": thread_id,
                "type": part.get("type"),
                "ns": part.get("ns", ()),
                "data": part.get("data"),
            },
        ),
    )
    return True


def create_debug_event(
    event_name: str,
    *,
    payload: Mapping[str, Any] | None = None,
    **context: object,
) -> dict[str, object]:
    """Create a JSON-compatible debug event payload.

    Args:
        event_name: Stable event name describing the debug payload.
        payload: Optional event-specific payload.
        **context: Additional event metadata.

    Returns:
        Sanitized dictionary ready for stream-writer emission or terminal output.
    """

    raw_event: dict[str, object] = {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "custom_debug",
        "event_name": event_name,
    }
    raw_event.update({key: value for key, value in context.items() if value is not None})
    if payload is not None:
        raw_event["payload"] = payload
    sanitized_event = _sanitize_for_console(raw_event)
    if isinstance(sanitized_event, dict):
        return sanitized_event
    return {
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "event_class": "custom_debug",
        "event_name": "debug_event_serialization_error",
        "payload": str(sanitized_event),
    }


def emit_custom_debug_event(
    event_name: str,
    *,
    payload: Mapping[str, Any] | None = None,
    **context: object,
) -> None:
    """Emit a custom LangGraph debug event through the stream writer when available.

    Args:
        event_name: Stable event name describing the debug payload.
        payload: Optional event payload.
        **context: Additional event metadata.
    """

    try:
        writer = get_stream_writer()
    except Exception:
        return

    if not callable(writer):
        return
    writer(create_debug_event(event_name, payload=payload, **context))


def _emit_json_line(payload: object) -> None:
    """Print a JSON payload as one console line.

    Args:
        payload: JSON-compatible payload to emit.
    """

    print(json.dumps(payload, ensure_ascii=False))


def _sanitize_for_console(value: object) -> object:
    """Convert arbitrary values into JSON-friendly console output.

    Args:
        value: Arbitrary Python value.

    Returns:
        JSON-compatible sanitized representation.
    """

    if value is None or isinstance(value, bool | int | float):
        return value
    if isinstance(value, str):
        return _truncate_text(_mask_security_numbers(value))
    if isinstance(value, Mapping):
        return {
            str(key): _sanitize_for_console(nested_value)
            for key, nested_value in value.items()
            if nested_value is not None
        }
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return [_sanitize_for_console(item) for item in value]
    if hasattr(value, "model_dump") and callable(value.model_dump):
        return _sanitize_for_console(value.model_dump())
    if hasattr(value, "dict") and callable(value.dict):
        return _sanitize_for_console(value.dict())
    return _truncate_text(_mask_security_numbers(str(value)))


def _summarize_values_payload(value: object) -> object:
    """Summarize a streamed `values` payload for standard console mode.

    Args:
        value: Raw streamed state payload.

    Returns:
        A compact JSON-compatible summary.
    """

    normalized_value = value
    if hasattr(normalized_value, "model_dump") and callable(normalized_value.model_dump):
        normalized_value = normalized_value.model_dump()
    elif hasattr(normalized_value, "dict") and callable(normalized_value.dict):
        normalized_value = normalized_value.dict()

    if not isinstance(normalized_value, Mapping):
        return normalized_value

    specialist_output_json = normalized_value.get("specialist_output_json")
    specialist_support_status = None
    if isinstance(specialist_output_json, str) and specialist_output_json.strip():
        try:
            specialist_output = json.loads(specialist_output_json)
        except json.JSONDecodeError:
            specialist_output = None
        if isinstance(specialist_output, Mapping):
            specialist_support_status = specialist_output.get("support_status")

    message_count = normalized_value.get("messages", [])

    return {
        "keys": sorted(str(key) for key in normalized_value.keys()),
        "router_intent": normalized_value.get("router_intent"),
        "patient_lookup_status": normalized_value.get("patient_lookup_status"),
        "specialist_support_status": specialist_support_status,
        "has_active_patient": normalized_value.get("active_patient") is not None,
        "has_last_response": bool(str(normalized_value.get("last_response") or "").strip()),
        "message_count": len(message_count) if isinstance(message_count, list) else 0,
    }


def _mask_security_numbers(text: str) -> str:
    """Mask fictional 8-digit security numbers before console emission.

    Args:
        text: Text that may contain patient identifiers.

    Returns:
        Text with 8-digit identifiers masked to preserve only the last four digits.
    """

    return _SECURITY_NUMBER_PATTERN.sub(r"****\2", text)


def _truncate_text(text: str) -> str:
    """Truncate long console strings while preserving that truncation occurred.

    Args:
        text: Text to potentially truncate.

    Returns:
        Original text when short enough, otherwise a truncated representation.
    """

    if len(text) <= _MAX_CONSOLE_TEXT_LENGTH:
        return text
    truncated_characters = len(text) - _MAX_CONSOLE_TEXT_LENGTH
    return (
        f"{text[:_MAX_CONSOLE_TEXT_LENGTH]}"
        f"… [truncated {truncated_characters} chars]"
    )
