"""Audit helpers for console-oriented observability."""

from __future__ import annotations

import json

from screening_agent.graph.state import AuditEvent



def emit_console_audit(event: AuditEvent) -> None:
    """Emit a structured audit event to stdout.

    Args:
        event: Serializable audit event generated by the graph or a tool.
    """

    print(json.dumps(event, ensure_ascii=False))
