"""Protocols and adapters describing control-model capabilities required by the graph."""

from __future__ import annotations

from typing import Any, Literal, Protocol, TypeVar, cast

from langchain.messages import AIMessage
from langchain_core.language_models.chat_models import BaseChatModel

StructuredOutputT = TypeVar("StructuredOutputT")


class StructuredOutputInvoker(Protocol[StructuredOutputT]):
    """Protocol for structured-output wrappers returned by a control model."""

    def invoke(self, messages: list[Any]) -> StructuredOutputT:
        """Produce a structured result for the provided message list.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            Structured output matching the configured schema.
        """


class ToolBoundControlModel(Protocol):
    """Protocol for a control model already bound to a tool set."""

    def invoke(self, messages: list[Any]) -> AIMessage:
        """Return an AI message, optionally containing tool calls.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            AI message generated by the bound control model.
        """


class ControlModel(Protocol):
    """Protocol implemented by models used for routing and control nodes."""

    def invoke(self, messages: list[Any]) -> AIMessage:
        """Return a plain AI response.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            AI message generated by the control model.
        """

    def bind_tools(self, tools: list[object]) -> ToolBoundControlModel:
        """Bind a tool list and return a tool-capable wrapper.

        Args:
            tools: Tool definitions exposed to the model.

        Returns:
            Tool-bound control model wrapper.
        """

    def with_structured_output(
        self,
        schema: type[StructuredOutputT],
    ) -> StructuredOutputInvoker[StructuredOutputT]:
        """Return a wrapper that emits structured output.

        Args:
            schema: Structured output schema type.

        Returns:
            Structured-output wrapper.
        """


class ChatModelControlAdapter:
    """Adapter that applies provider-specific LangChain options consistently.

    This wrapper keeps the rest of the graph working against the lightweight
    `ControlModel` protocol while still allowing provider-specific features such
    as strict tool binding or stricter structured-output modes.
    """

    def __init__(
        self,
        model: BaseChatModel,
        *,
        backend: Literal["openai", "openrouter", "openai_compatible"],
    ) -> None:
        """Store the wrapped chat model and provider kind.

        Args:
            model: Underlying LangChain chat model.
            backend: Provider family used to tune strict options.
        """

        self._model = model
        self._backend = backend

    def invoke(self, messages: list[Any]) -> AIMessage:
        """Return a plain AI response from the wrapped chat model.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            AI message generated by the provider model.
        """

        return self._model.invoke(messages)

    def bind_tools(self, tools: list[object]) -> ToolBoundControlModel:
        """Bind tools using the strictest supported provider settings.

        Args:
            tools: Tool definitions exposed to the model.

        Returns:
            Tool-bound model wrapper.
        """

        bind_kwargs: dict[str, object] = {}
        if self._backend in {"openai", "openrouter"}:
            bind_kwargs["strict"] = True
        try:
            return cast(ToolBoundControlModel, self._model.bind_tools(tools, **bind_kwargs))
        except TypeError:
            return cast(ToolBoundControlModel, self._model.bind_tools(tools))

    def with_structured_output(
        self,
        schema: type[StructuredOutputT],
    ) -> StructuredOutputInvoker[StructuredOutputT]:
        """Return structured output using provider-specific strict settings.

        Args:
            schema: Structured output schema type.

        Returns:
            Structured-output wrapper.
        """

        structured_kwargs: dict[str, object] = {}
        if self._backend == "openrouter":
            structured_kwargs["method"] = "json_schema"
            structured_kwargs["strict"] = True
        elif self._backend == "openai":
            structured_kwargs["strict"] = True
        try:
            return cast(
                StructuredOutputInvoker[StructuredOutputT],
                self._model.with_structured_output(schema, **structured_kwargs),
            )
        except TypeError:
            return cast(
                StructuredOutputInvoker[StructuredOutputT],
                self._model.with_structured_output(schema),
            )
