"""Protocols describing the control-model capabilities required by the graph."""

from __future__ import annotations

from typing import Any, Protocol, TypeVar

from langchain.messages import AIMessage

StructuredOutputT = TypeVar("StructuredOutputT")


class StructuredOutputInvoker(Protocol[StructuredOutputT]):
    """Protocol for structured-output wrappers returned by a control model."""

    def invoke(self, messages: list[Any]) -> StructuredOutputT:
        """Produce a structured result for the provided message list.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            Structured output matching the configured schema.
        """


class ToolBoundControlModel(Protocol):
    """Protocol for a control model already bound to a tool set."""

    def invoke(self, messages: list[Any]) -> AIMessage:
        """Return an AI message, optionally containing tool calls.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            AI message generated by the bound control model.
        """


class ControlModel(Protocol):
    """Protocol implemented by models used for routing and control nodes."""

    def invoke(self, messages: list[Any]) -> AIMessage:
        """Return a plain AI response.

        Args:
            messages: LangChain-compatible message list.

        Returns:
            AI message generated by the control model.
        """

    def bind_tools(self, tools: list[object]) -> ToolBoundControlModel:
        """Bind a tool list and return a tool-capable wrapper.

        Args:
            tools: Tool definitions exposed to the model.

        Returns:
            Tool-bound control model wrapper.
        """

    def with_structured_output(
        self,
        schema: type[StructuredOutputT],
    ) -> StructuredOutputInvoker[StructuredOutputT]:
        """Return a wrapper that emits structured output.

        Args:
            schema: Structured output schema type.

        Returns:
            Structured-output wrapper.
        """
